// Generated by CoffeeScript 1.9.3
(function() {
  var Pagination, countLength;

  countLength = function(obj) {
    var count, i, j, len;
    count = 0;
    for (j = 0, len = obj.length; j < len; j++) {
      i = obj[j];
      if (obj.hasOwnProperty(i)) {
        count++;
      }
    }
    return count;
  };

  Pagination = (function() {
    function Pagination(options) {
      this.options = options;
      this.remote = options.remote;
      this.url = this.remote ? options.url : '';
      this.values = options.values ? options.values : [];
      this.method = options.method ? options.method : 'GET';
      this.width = options.width;
      this.height = options.height;
      this.limit = options.limit;
      this.headerRow = options.headerRow;
      this.buttons = options.buttons ? options.buttons : {};
      this.maxPage = Math.ceil(this.values.length / this.limit) === 0 ? 1 : Math.ceil(this.values.length / this.limit);
      this.rowIds = [];
      this.pageIds = [];
      this.buttonIds = [];
      if (this.remote) {
        retrieve();
      }
    }

    Pagination.prototype.getStartingIndex = function(pageNum) {
      return (pageNum - 1) * this.limit;
    };

    Pagination.prototype.retrieve = function() {
      return $.ajax({
        url: this.url,
        method: this.method,
        success: function(data, textStatus, jqXHR) {
          this.values = data;
          this.maxPage = Math.ceil(data.length / this.limit);
        }
      });
    };

    Pagination.prototype.setValues = function(val) {
      this.values = val;
    };

    Pagination.prototype.deleteRow = function(id) {
      $("#row-" + id).remove();
    };

    Pagination.prototype.inflate = function(jqObj, pageNum) {
      var bar, bi, buttonId, i, j, k, l, len, len1, len2, m, pageId, pi, ref, ref1, ref2, ref3, self, startingIdx, table, theadrow, thisPage;
      if (pageNum < 1 || pageNum > this.maxPage) {
        return;
      }
      startingIdx = this.getStartingIndex(pageNum);
      jqObj.empty();
      self = this;
      table = $('<table class="table" id="pagination-table"><thead><tr></tr></thead><tbody></tbody></table>');
      bar = $('<div class="pagination pagination-centered" id="pagination-bar"><ul></ul></div>');
      $('#prev').off('click');
      $('#next').off('click');
      ref = this.pageIds;
      for (j = 0, len = ref.length; j < len; j++) {
        pi = ref[j];
        $("#to-page-" + pi).off('click');
      }
      this.pageIds = [];
      ref1 = this.buttonIds;
      for (k = 0, len1 = ref1.length; k < len1; k++) {
        bi = ref1[k];
        $("" + bi).off('click');
      }
      this.buttonIds = [];
      this.rowIds = [];
      theadrow = table.children('thead').children('tr');
      theadrow.append('<th></th>');
      $.each(this.headerRow, function(idx, e) {
        theadrow.append($('<th>').text(e));
      });
      if (countLength(this.buttons) !== 0) {
        theadrow.append('<th></th>');
      }
      thisPage = this.values.slice(startingIdx, +(startingIdx + this.limit - 1) + 1 || 9e9);
      buttonId = 0;
      $.each(thisPage, function(idx, eachObj) {
        var row;
        row = $("<tr id=\"row-" + eachObj.id + "\"></tr>").append('<td><input type="checkbox" class="rowSelect" /></td>');
        self.rowIds.push("row-" + eachObj.id);
        row.data('id', eachObj.id);
        row.data('rowData', eachObj.data);
        $.each(eachObj.data, function(idx, eachCell) {
          return row.append($('<td>').text(eachCell));
        });
        $.each(self.buttons, function(name, handler) {
          buttonId = "button-" + (buttonId++);
          row.append("<td><button class=\"btn btn-small\" id=" + buttonId + ">" + name + "</button></td>");
          $(document.body).on('click', "#" + buttonId, function(e) {
            var parentRow;
            e.preventDefault();
            parentRow = $(this).parent().parent();
            handler(parentRow.data('id'), parentRow.data('rowData'));
          });
          self.buttonIds.push("#" + buttonId);
        });
        table.children('tbody').append(row);
      });
      bar.children('ul').append('<li><a href="javascript:void(0);" id="first-page">&laquo;</a></li>');
      bar.children('ul').append('<li><a href="javascript:void(0);" id="prev-page"><</a></li>');
      for (i = l = 1, ref2 = this.maxPage; 1 <= ref2 ? l <= ref2 : l >= ref2; i = 1 <= ref2 ? ++l : --l) {
        bar.children('ul').append("<li><a href=\"javascript:void(0);\" id=\"to-page-" + i + "\">" + i + "</a></li>");
        self.pageIds.push(i);
      }
      bar.children('ul').append('<li><a href="javascript:void(0);" id="next-page">></a></li>');
      bar.children('ul').append('<li><a href="javascript:void(0);" id="last-page">></a></li>');
      jqObj.append(table);
      jqObj.append(bar);
      $('#first-page').click(function(e) {
        e.preventDefault();
        $('#pagination-table').parent().paginate('inflate', 1);
      });
      $('#prev-page').click(function(e) {
        e.preventDefault();
        $('#pagination-table').parent().paginate('inflate', pageNum - 1);
      });
      ref3 = this.pageIds;
      for (m = 0, len2 = ref3.length; m < len2; m++) {
        pageId = ref3[m];
        $("#to-page-" + pageId).click(function(e) {
          e.preventDefault();
          $('#pagination-table').parent().paginate('inflate', pageId);
        });
      }
      $('#next-page').click(function(e) {
        e.preventDefault();
        $('#pagination-table').parent().paginate('inflate', pageNum + 1);
      });
      return $('#last').click(function(e) {
        e.preventDefault();
        $('#pagination-table').parent().paginate('inflate', this.maxPage);
      });
    };

    return Pagination;

  })();

  
$.fn.paginate = function (options) {
	if (typeof(pg) !== "undefined") {
		if (options === "get") {
			return pg;
		}
		else if (options === "inflate") {
			pg.inflate(this, arguments[1]);
			return this;
		}
		else if (options === "setValues") {
			pg.setValues(arguments[1]);
			return this;
		}
		else if (options === "deleteRow") {
			pg.deleteRow(arguments[1]);
			return this;
		}
	}
	pg = new Pagination(options);
	pg.inflate(this, 1);
	return this;
};

}).call(this);
